pipelines:
  custom:
    mirror-to-uis:
      - step: &mirror-to-uis
          name: "Mirror to git.uis"
          script:
            # Tell git who we are
            - git config user.email "mws-robotmail@uis.cam.ac.uk"
            - git config user.name "MWS Bitbucket Robot"
            # Ask git-uis about ourselves
            - ssh uis@git.uis.cam.ac.uk info
            # We need a full clone when mirroring -> git.uis. Change into the
            # git directory so that we're effectively operating on a bare repo.
            - cd .git
            - git fetch --update-head-ok origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
            # Mirror ourselves to git-uis
            - git push --prune uis@git.uis.cam.ac.uk:mwsv3/webapp +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
  default:
    - step: *mirror-to-uis
